language: ruby
rvm:
  - 2.0.0
  - 2.4.0
  - jruby-head
  - rbx-2.2.7

install: bundle install --jobs=3 --deployment --without development
script: bundle exec rspec

git:
  depth: 3

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2.2.7
