language: ruby

dist: trusty

rvm:
  - 2.0.0
  - 2.4.1
  - jruby-head
  - rubinius-3.15

install: bundle install --jobs=3 --deployment --without development

script: bundle exec rake spec && bash spec/build/gem_build_test.sh

git:
  depth: 3

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rubinius-3.15
