language: ruby

dist: trusty

rvm:
  - 2.0.0
  - 2.4.0
  - jruby-9.1.5.0
  - rbx-2.2.7

install: bundle install --jobs=3 --deployment --without development

script: bundle exec rake spec

git:
  depth: 3

matrix:
  allow_failures:
    - rvm: jruby-9.1.5.0
    - rvm: rbx-2.2.7
