language: ruby

dist: trusty

rvm:
  - 2.0.0
  - 2.4.1
  - jruby-9.1.12.0

install: bundle install --jobs=3 --deployment --without development

script: bundle exec rake spec_all_locales && bash spec/build/gem_build_test.sh

git:
  depth: 3

matrix:
  allow_failures:
    - rvm: jruby-9.1.12.0
