language: ruby

rvm:
  - 2.0.0
  #- 2.5.0
  - jruby-9.1.9.0
  - jruby-head

before_install:
  - gem update --system
  - gem install bundler
install: bundle install --jobs=3 --deployment --without development

script: bundle exec rake spec_all_locales && bash spec/build/gem_build_test.sh

git:
  depth: 3

# matrix:
#   allow_failures:
#     - rvm: jruby-9.1.9.0
